### PR TITLE
Nail down activerecord

### PR DESCRIPTION
**Pull request by dgutov**
This at least allows me to run ActiveRecord integration specs to completion.

### CODE REVIEW

**Comment by igrigorik** [comment]
Can we drop the AMQP change here? :)

**Comment by dgutov** [comment]
Okay, I'm lost now. :) Is the point that you want to be able to revert either of them quickly?

**Comment by igrigorik** [comment]
Yes, isolated changes make it much easier to review code and to revert if needed.

**Comment by dgutov** [comment]
Okay then. Force-pushed.

**Comment by dgutov** [comment]
@igrigorik Ping?

**Comment by igrigorik** [comment]
Thanks for the reminder :)

**Pull request merged**
