### PR TITLE
Integrate with Travis CI

### PR DESCRIPTION
**Pull request by dgutov**
This adds `.travis.yml`, fixes some broken specs and updates the outdated specs to work in RSpec 3.2 (which is what its Gemfile entry without specific version asks for).

The main motivation is for everyone to be able to see the state of affairs WRT ActiveRecord versions compatibility, and to run every pull request purported to fix it against multiple AR versions. See the current build results here:

https://travis-ci.org/dgutov/em-synchrony/builds/54472508

### CODE REVIEW

**Comment by igrigorik** [comment]
Awesome stuff, thanks Dmitry!

**Comment by dgutov** [comment]
Thanks for merging.

Now, to make this work you need to visit https://travis-ci.org/, log in and enable it for this repository (I only did that for my fork). I'll add a badge in a separate pull request.

**Comment by igrigorik** [comment]
@dgutov should be enabled now.

**Comment by dgutov** [comment]
Yep, looks fine.

**Pull request merged**
